-- [[ IMPORTS ]]
require('vars')
require('opts')
require('keys')
require('plugs')

-- [[ PLUGINS ]]
require('nvim-atpairs')
require('nvim-comment')
require('nvim-gitsigns')
require('nvim-gitblame')
require('nvim-bufferline')
require('nvim-tr')
require('nvim-null-ls')
require('nvim-lualine')
require('nvim-telescope')
require('nvim-ts')
require('nvim-lsp')
require('nvim-completion')
require('nvim-autotag')
